import type { BlogPost } from '@/content/types';

export const post: BlogPost = {
  slug: 'website-redesign-checklist',
  title: 'The Website Redesign Checklist That Protects Your SEO',
  metaTitle: 'Website Redesign Checklist That Protects SEO',
  metaDescription:
    'A practical website redesign checklist: benchmark, map every URL, protect ranking pages, redirect properly and monitor the launch without losing traffic.',
  category: 'Strategy',
  tags: ['Website Redesign', 'SEO', 'Migration', 'WordPress', 'Planning'],
  publishedAt: '2026-05-27',
  readingMinutes: 11,
  authorSlug: 'jahanzaib-abid',
  excerpt:
    'Redesigns rarely lose traffic because of the new design — they lose it because of what happened to URLs, content and internal links. Here is the checklist we work through on every rebuild.',
  relatedServiceSlugs: [
    'website-redesign',
    'seo-services',
    'website-migration-replatforming',
    'ui-ux-design',
  ],
  relatedPostSlugs: [
    'core-web-vitals-wordpress-guide',
    'website-maintenance-guide',
    'how-much-does-a-website-cost',
  ],
  body: [
    {
      type: 'p',
      text: 'A redesign is one of the fastest ways to improve how a business is perceived — and one of the fastest ways to lose the organic traffic it already had. We regularly speak to owners a few weeks after a relaunch who tell us the same story: the site looks far better, everyone internally is pleased, and enquiries have quietly halved. Nothing obvious is broken, so nobody knows where to look.',
    },
    {
      type: 'p',
      text: 'The uncomfortable truth is that rankings almost never collapse because of the new design. They collapse because of what happened around it — URLs that changed without redirects, pages that were cut because they looked dated, headings and internal links that were rewritten out of existence, or a staging site that shipped with search engines still blocked. Every one of those is preventable with a plan made before the first mockup.',
    },
    {
      type: 'p',
      text: 'Across 50 delivered builds — 42 on WordPress, 5 on Bubble.io, one hybrid build and one custom Next.js application — we have settled on a sequence that keeps the visible improvement and the invisible equity. This is that checklist, in the order we actually run it. Work through it and a redesign becomes a step up rather than a reset.',
    },

    { type: 'h2', text: 'Why redesigns lose traffic in the first place' },
    {
      type: 'p',
      text: 'Search engines do not rank a design. They rank pages: specific URLs with specific content, linked to from specific places, with a history of satisfying specific queries. A redesign touches all four of those things at once, which is why it carries more risk than any other routine project a business runs on its website.',
    },
    {
      type: 'p',
      text: 'When we audit a redesign that went wrong, the cause is nearly always in this list:',
    },
    {
      type: 'ul',
      items: [
        'URLs changed to a new structure with no redirect map, so every ranking page returns a 404.',
        'Content was trimmed for visual tidiness, removing the 800-word service pages that were doing the ranking.',
        'Headings became images or decorative text, so the on-page signals disappeared even though the words are still visible.',
        'Internal linking was simplified into a slim navigation, cutting deep pages off from the rest of the site.',
        'Title tags and meta descriptions were regenerated by the new theme instead of being carried across.',
        'The staging site launched with noindex or a Disallow rule still in robots.txt.',
        'Page speed regressed because the new build ships heavier images, more fonts and more third-party scripts.',
      ],
    },
    {
      type: 'callout',
      title: 'Treat SEO as a design input, not a launch task',
      text: 'If the first SEO conversation happens the week before go-live, the expensive decisions — URL structure, page inventory, content depth, navigation — have already been made. Bring the constraints into the wireframe stage and they cost nothing.',
    },

    { type: 'h2', text: 'Step 1: Benchmark and archive before anything changes' },
    {
      type: 'p',
      text: 'You cannot protect what you have not measured. Before a single page is designed, capture a complete picture of the current site. This takes an afternoon and it is the only reason you will be able to answer the question everyone asks two months later: did the redesign actually help?',
    },

    { type: 'h3', text: 'Crawl the live site and keep the crawl' },
    {
      type: 'p',
      text: 'Run a full crawl of the existing site and export it. You want every URL that returns a 200, along with its title tag, meta description, H1, word count, canonical tag and status code. Export your XML sitemap separately, and pull the list of URLs that have earned impressions in the last twelve months from Search Console. Those three lists together are your inventory — and the Search Console list matters most, because it includes pages your crawler may never reach through navigation.',
    },
    {
      type: 'p',
      text: 'Also export your backlink profile. Pages with external links pointing at them are the ones where a broken redirect costs real money, and they deserve individual attention rather than a bulk rule.',
    },

    { type: 'h3', text: 'Record the baseline you will be judged against' },
    {
      type: 'p',
      text: 'Note organic sessions, organic conversions, impressions and average position for the previous three months, plus your Core Web Vitals field data. Save a copy of the numbers somewhere outside the analytics tool, because tracking configuration often changes during a rebuild and you will want a fixed reference point. Where the site is being replatformed entirely, take screenshots of your top twenty pages too — they settle a surprising number of arguments about what the old site actually said.',
    },

    { type: 'h2', text: 'Step 2: Decide what happens to every single URL' },
    {
      type: 'p',
      text: 'This is the step that separates a clean redesign from a painful one. Take your inventory into a spreadsheet and give every old URL a decision: it stays as it is, it moves to a new URL, it merges into another page, or it is retired. There is no fifth option, and no URL is allowed to be blank.',
    },
    {
      type: 'p',
      text: 'Our default advice is to keep URLs unchanged wherever the page is genuinely staying. A prettier slug is worth very little; a redirect chain is a permanent tax. Change the structure only when the old one is actively harmful — duplicate paths, dates baked into evergreen article URLs, or a taxonomy nobody understands.',
    },
    {
      type: 'table',
      headers: ['Situation', 'What to do with the old URL', 'Response'],
      rows: [
        [
          'Page stays and keeps its purpose',
          'Leave the URL exactly as it is',
          'None needed',
        ],
        [
          'Page stays but the slug or folder changes',
          'Point the old URL at its direct replacement',
          '301 permanent',
        ],
        [
          'Several thin pages merge into one stronger page',
          'Redirect every old URL to the merged page',
          '301 permanent',
        ],
        [
          'Page is retired with no direct equivalent',
          'Redirect to the closest parent category, never the home page',
          '301 permanent',
        ],
        [
          'Page is genuinely obsolete and has no links or traffic',
          'Remove it, drop internal links, let it return Gone',
          '410 Gone',
        ],
        [
          'Section is offline briefly during a phased launch',
          'Signal that the move is not final',
          '302 temporary',
        ],
        [
          'Domain change, or HTTP moving to HTTPS',
          'Map every URL one-to-one at the server',
          '301 permanent',
        ],
      ],
    },
    {
      type: 'p',
      text: 'Two rules save more traffic than everything else here. First, never bulk-redirect a set of retired pages to the home page — search engines treat that as a soft 404 and the equity evaporates. Second, redirect old URL to final URL directly. Chains of two or three hops accumulate quickly across successive redesigns and slow every request that follows them.',
    },
    {
      type: 'p',
      text: 'On an Apache-hosted WordPress site the map itself is unglamorous, which is exactly the point:',
    },
    {
      type: 'code',
      language: 'apache',
      code: [
        '# Place above the default WordPress rewrite block in .htaccess.',
        'RewriteEngine On',
        '',
        '# One line per individually mapped page.',
        'Redirect 301 /web-design-agency /services/website-design',
        'Redirect 301 /about-us-2 /about',
        '',
        '# Pattern rule: the whole old news folder becomes /blog/.',
        'RewriteRule ^news/(.*)$ /blog/$1 [R=301,L]',
        '',
        '# Force a single canonical host and scheme.',
        'RewriteCond %{HTTP_HOST} ^www\\.example\\.com [NC,OR]',
        'RewriteCond %{HTTPS} off',
        'RewriteRule ^(.*)$ https://example.com/$1 [R=301,L]',
      ].join('\n'),
    },

    { type: 'h2', text: 'Step 3: Protect the pages that already earn' },
    {
      type: 'p',
      text: 'Redesigns tend to be led by the home page, because that is what everyone looks at in the kick-off meeting. In our experience the pages that actually bring in enquiries are service pages, location pages and long-form articles — the ones nobody presents in a mockup review. Identify your top twenty organic landing pages early and make them a formal part of the design scope.',
    },
    {
      type: 'p',
      text: 'For each of those pages, carry the signals across deliberately rather than hoping the new template reproduces them:',
    },
    {
      type: 'ul',
      items: [
        'Keep the title tag and meta description, or improve them consciously — do not let a theme regenerate them.',
        'Keep one H1 per page, and keep the heading hierarchy without skipping levels.',
        'Keep the substantive body copy. If a page ranks on 900 words, a 200-word redesign of it will not hold.',
        'Keep the internal links that point into the page, including contextual links from articles.',
        'Keep structured data — organisation, service, article, FAQ and breadcrumb markup all need porting.',
        'Keep image alt text, and keep the images themselves indexable at sensible file names.',
      ],
    },
    {
      type: 'p',
      text: 'Where content genuinely is weak, improve it during the redesign rather than deleting it. Consolidating five thin pages into one authoritative guide is usually a gain. Quietly dropping five thin pages that collectively earned a fifth of your traffic is a loss you will feel for months.',
    },

    { type: 'h2', text: 'Step 4: Rebuild the technical foundations, not just the visuals' },
    {
      type: 'p',
      text: 'A redesign is the cheapest opportunity you will ever get to fix the technical layer, because everything is being touched anyway. Retrofitting the same work into a live site later costs several times more.',
    },

    { type: 'h3', text: 'Performance is part of the brief' },
    {
      type: 'p',
      text: 'Set a performance budget before the design is signed off, and hold the build to Google’s published Core Web Vitals thresholds: Largest Contentful Paint under 2.5 seconds, Interaction to Next Paint under 200 milliseconds, and Cumulative Layout Shift below 0.1. Those numbers are easy to hit when the hero image is sized properly, fonts are self-hosted with explicit dimensions on media, and third-party scripts are counted. They are very hard to retrofit into a page builder layout with six sliders and four tracking tags.',
    },

    { type: 'h3', text: 'Get the indexing rules right' },
    {
      type: 'p',
      text: 'Every redesign needs an explicit plan for canonical tags, pagination, faceted URLs and any parameter-driven pages the new build introduces. Filters that generate URL parameters are the most common accidental duplication we find after a launch, particularly on WooCommerce stores where colour and size filters can multiply a 200-product catalogue into thousands of crawlable variants.',
    },

    { type: 'h3', text: 'Plan multilingual structure up front' },
    {
      type: 'p',
      text: 'If the site serves more than one language, decide the URL structure and the hreflang strategy before build, not after. We have shipped sites in English, German, French, Italian, Hebrew, Polish, Dutch and Norwegian, and the pattern is consistent: language handling bolted on at the end produces missing return tags, untranslated meta data and duplicate home pages. Right-to-left builds in particular — such as our Hebrew e-learning work — need the layout tested in both directions from the first template, not the last sprint.',
    },

    { type: 'h2', text: 'Step 5: The pre-launch checklist' },
    {
      type: 'p',
      text: 'Run this in order on the staging site in the days before go-live. Every item is something we have seen break a real launch.',
    },
    {
      type: 'ol',
      items: [
        'Crawl the staging site and compare the URL inventory against your old-site export — anything missing needs a decision, not a shrug.',
        'Test the redirect map in bulk by running every old URL through a crawler and confirming a single 301 hop to a 200 response.',
        'Confirm no redirect resolves to a 404, a redirect chain, or the home page by accident.',
        'Check that every page has a unique title tag and meta description, and that none are empty or duplicated across templates.',
        'Verify one H1 per page and a heading hierarchy that never skips a level.',
        'Validate structured data on the templates that carry it, including breadcrumbs and FAQ markup.',
        'Regenerate the XML sitemap so it lists only final, indexable URLs, and confirm robots.txt points at it.',
        'Remove the staging noindex directive and the Disallow rule — check both, they live in different places.',
        'Confirm analytics and conversion tracking fire on the new templates, including the form success state.',
        'Test forms end to end and confirm the enquiry actually arrives in the inbox that receives it.',
        'Run Lighthouse on the templates that matter — home, service, article, contact — on a throttled mobile profile.',
        'Check the site at 360px width for horizontal overflow, and tab through it to confirm visible focus states.',
        'Take a full backup of the old site and database, and keep it until you are three months clear of launch.',
      ],
    },
    {
      type: 'callout',
      title: 'Launch early in the week',
      text: 'Go live on a Tuesday or Wednesday morning, never on a Friday afternoon. The first 48 hours produce most of the issues, and you want the whole team available rather than discovering a broken redirect map on Monday.',
    },

    { type: 'h2', text: 'Step 6: Launch day and the first 30 days' },
    {
      type: 'p',
      text: 'The work is not finished when DNS propagates. A redesign typically causes a visible fluctuation in rankings for a few weeks while search engines re-crawl and re-evaluate the new pages. That is normal. What is not normal is a decline that does not recover, and the only way to tell the difference is to watch closely.',
    },
    {
      type: 'ul',
      items: [
        'Submit the new XML sitemap in Search Console on launch day and request indexing for your most important pages.',
        'Watch the Pages report daily for the first fortnight — a spike in Not Found or Redirect Error is your early warning.',
        'Fix newly reported 404s by adding them to the redirect map, and keep the map under version control.',
        'Compare organic landing-page performance against your baseline weekly, not daily; daily data is too noisy to act on.',
        'Re-run Core Web Vitals field data after 28 days, once real user data has accumulated on the new build.',
        'Keep the old site accessible internally for a quarter so you can settle any question about what changed.',
      ],
    },

    { type: 'h2', text: 'How we approach redesigns at Tekvion' },
    {
      type: 'p',
      text: 'We start every redesign with an inventory and a redirect map, before design work begins. It is not the glamorous part of the project, but it determines whether the launch is uneventful. The inventory tells us which pages must survive; the map tells the build team which URLs are fixed and which are free to change. Design then works within those constraints, which turns out to be a creative help rather than a hindrance — it forces early clarity about what each page is actually for.',
    },
    {
      type: 'p',
      text: 'Scale changes the emphasis but not the method. A multi-location retail site with hundreds of showroom pages needs template-level redirect rules and careful handling of the store locator; a specialist clinic site needs its appointment flows and German-language meta data carried across intact; a Dutch WooCommerce store needs its product URLs, category structure and filter parameters mapped before a single template is rebuilt. Same checklist, different pressure points.',
    },
    {
      type: 'p',
      text: 'We also insist on a staging environment that mirrors production, a full backup that is verified rather than assumed, and a launch window with people available. Most redesign disasters we have been asked to rescue were not caused by a lack of skill. They were caused by launching in a hurry, on a Friday, with no way back.',
    },

    { type: 'h2', text: 'Where to start' },
    {
      type: 'p',
      text: 'If your current site is dated but earning, the goal is not a blank page — it is a rebuild that keeps every signal you have accumulated and improves everything you have not. Start with the inventory this week: crawl the site, pull your Search Console data, and list the twenty pages you cannot afford to lose. That single document will shape the entire project.',
    },
    {
      type: 'p',
      text: 'If you would rather not run it alone, this is exactly the work we do. Our website redesign service covers the inventory, redirect mapping and rebuild end to end; our SEO services cover the audit, on-page carry-over and post-launch monitoring; our migration and replatforming work handles the harder cases where the CMS or domain is changing too; and our UI/UX design practice makes sure the new site is genuinely easier to use, not just newer to look at. Tell us what your current site earns and we will tell you honestly what a redesign should protect.',
    },
  ],
};
